eureka:
  client:
    serviceUrl:
      defaultZone: http://alice:1234@localhost:7555/eureka/
  instance:
    hostname: localhost
   # prefer-ip-address: false                       # 开启ip地址定义注册中心，默认值为false
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8556
spring:
  application:
    name: microservice-consumer-movie-understanding-metadata   #提供给其他人的服务名字  其他地方可以用这个调用
logging:
  level: info
