server:
  port: 7555

spring:
  application:
    name: urk-server

security:
  basic:
    enabled: true                        # 开启 基于HTTP basic 的认证
  user:
    name: alice                           #配置登陆的账户是alice
    password: 1234


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false                       # false代表不向注册中心注册自己          #   高可用实际上就是将自己作为
    fetchRegistry: false                             # 维护服务，不需要检索服务               #   服务向其他服务注册中心注册自己
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
       enabled: true

