eureka:
    client:
        serviceUrl:
              defaultZone: http://alice:1234@localhost:7555/eureka/    # 指定服务注册中心的地址
        instance:
            hostname: localhost
            status-page-url-path: /index                     # 自定义url位置

spring:
    application:
        name: Eureka-Consumer-feign            # 服务命名

server:
     port: 7666

logging:
        level:
             com :
               kuliao:
                   eurek :
                       infeign:
                         UserFeignClient: debug
feign:
  hystrix:
    enabled: true


#eureka.client.service-url.defaultZone=http://alice:1234@localhost:7555/eureka/
#eureka.client.instance.hostname= localhost
#eureka.client.instance.status-page-url-path= /index
#spring.application.name= Eureka-Consumer-feign
#server.port=7666
#logging.level.UserFeignClient=debug

