eureka:
  client:
    serviceUrl:
      defaultZone: http://alice:1234@localhost:7555/eureka/    # 指定服务注册中心的地址
server:
  port: 7999
zuul:
  routes:
    api-a-url:
        path: /api-aa-url/**
        url: http://localhost:7558/

spring:
    application:
        name: api-gateway         # 服务命名